import type { CivDef } from './types';

export const CIVS: Record<string, CivDef> = {
  academy: {
    id: 'academy',
    name: 'Академія',
    icon: '🏛️',
    color: '#3b82f6',
    description: 'Стародавня школа мудрості та наукового знання.',
    bonus: '+4📚/хід, Вчені коштують вдвічі менше, дешевша наука',
    startUnits: ['warrior', 'warrior', 'scholar', 'scholar'],
    kBonus: 4, eBonus: 0, iBonus: 1, coinsBonus: 0,
    techCostPct: -20,
    forestPassable: false,
    riverPassable: false,
  },
  legion: {
    id: 'legion',
    name: 'Легіон',
    icon: '⚔️',
    color: '#ef4444',
    description: 'Дисциплінована військова держава, загартована у боях.',
    bonus: 'Воїни +60% HP, старт із 4 воїнами, +2⚡/хід',
    startUnits: ['warrior', 'warrior', 'warrior', 'warrior', 'archer'],
    kBonus: 0, eBonus: 2, iBonus: 0, coinsBonus: 0,
    techCostPct: 0,
    forestPassable: false,
    riverPassable: false,
  },
  innovators: {
    id: 'innovators',
    name: 'Новатори',
    icon: '💡',
    color: '#a855f7',
    description: 'Народ невтомних дослідників та винахідників.',
    bonus: '+3💡/хід, -25% вартість технологій, AI юніт безкоштовно',
    startUnits: ['warrior', 'scholar', 'aiUnit'],
    kBonus: 2, eBonus: 0, iBonus: 3, coinsBonus: 0,
    techCostPct: -25,
    forestPassable: false,
    riverPassable: true,
  },
  natureFolk: {
    id: 'natureFolk',
    name: 'Лісовий Народ',
    icon: '🌿',
    color: '#10b981',
    description: 'Єдиний з природою народ, що живе у лісах та річках.',
    bonus: 'Всі юніти проходять ліси та річки, +3⚡/хід, юніти лікуються у лісі',
    startUnits: ['warrior', 'warrior', 'scholar', 'archer'],
    kBonus: 0, eBonus: 3, iBonus: 0, coinsBonus: 2,
    techCostPct: 0,
    forestPassable: true,
    riverPassable: true,
  },
};
