// <auto-generated />
using System;
using LTropik.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LTropik.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LTropik.Domain.Entities.AppNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("text")
                        .HasColumnName("action_url");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_app_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_app_notifications_user_id");

                    b.ToTable("app_notifications", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_app_settings");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.AttendanceAndGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attendance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attendance");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_id");

                    b.Property<DateOnly>("LessonDate")
                        .HasColumnType("date")
                        .HasColumnName("lesson_date");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_attendance_and_grades");

                    b.HasIndex("GradeId")
                        .HasDatabaseName("ix_attendance_and_grades_grade_id");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_attendance_and_grades_lesson_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_attendance_and_grades_student_id");

                    b.ToTable("attendance_and_grades", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CoinsReward")
                        .HasColumnType("integer")
                        .HasColumnName("coins_reward");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<int>("ConditionValue")
                        .HasColumnType("integer")
                        .HasColumnName("condition_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_badges");

                    b.ToTable("badges", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bookmarks");

                    b.HasIndex("UserId", "Type", "RefId")
                        .IsUnique()
                        .HasDatabaseName("ix_bookmarks_user_id_type_ref_id");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("GradeScaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_scale_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("GradeScaleId")
                        .HasDatabaseName("ix_courses_grade_scale_id");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.CourseProgress", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.HasKey("StudentId", "LessonId")
                        .HasName("pk_course_progresses");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_course_progresses_lesson_id");

                    b.ToTable("course_progresses", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.CourseReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_course_reviews");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_course_reviews_student_id");

                    b.HasIndex("CourseId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_course_reviews_course_id_student_id");

                    b.ToTable("course_reviews", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.CourseStudent", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int>("BalanceLessons")
                        .HasColumnType("integer")
                        .HasColumnName("balance_lessons");

                    b.Property<DateTimeOffset?>("SubscriptionEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_ends_at");

                    b.HasKey("CourseId", "StudentId")
                        .HasName("pk_course_students");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_course_students_student_id");

                    b.ToTable("course_students", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.CourseTeacher", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("CourseId", "TeacherId")
                        .HasName("pk_course_teachers");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_course_teachers_teacher_id");

                    b.ToTable("course_teachers", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.CustomProfileField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_type");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.HasKey("Id")
                        .HasName("pk_custom_profile_fields");

                    b.ToTable("custom_profile_fields", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.DailyQuest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CoinsReward")
                        .HasColumnType("integer")
                        .HasColumnName("coins_reward");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_daily_quests");

                    b.ToTable("daily_quests", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.DirectMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_direct_messages");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_direct_messages_receiver_id");

                    b.HasIndex("SenderId", "ReceiverId")
                        .HasDatabaseName("ix_direct_messages_sender_id_receiver_id");

                    b.ToTable("direct_messages", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.EnrollmentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("ResponseNote")
                        .HasColumnType("text")
                        .HasColumnName("response_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_enrollment_requests");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_enrollment_requests_student_id");

                    b.HasIndex("CourseId", "StudentId")
                        .HasDatabaseName("ix_enrollment_requests_course_id_student_id");

                    b.ToTable("enrollment_requests", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Flashcard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("back");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("front");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_flashcards");

                    b.HasIndex("SetId")
                        .HasDatabaseName("ix_flashcards_set_id");

                    b.ToTable("flashcards", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.FlashcardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_flashcard_sets");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_flashcard_sets_lesson_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_flashcard_sets_user_id");

                    b.ToTable("flashcard_sets", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.GradeScale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_grade_scales");

                    b.ToTable("grade_scales", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.GradeScaleValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPassing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passing");

                    b.Property<Guid>("ScaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("scale_id");

                    b.Property<string>("ValueString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_string");

                    b.HasKey("Id")
                        .HasName("pk_grade_scale_values");

                    b.HasIndex("ScaleId")
                        .HasDatabaseName("ix_grade_scale_values_scale_id");

                    b.ToTable("grade_scale_values", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.GroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("GroupId", "StudentId")
                        .HasName("pk_group_members");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_group_members_student_id");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Homework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder_sent");

                    b.HasKey("Id")
                        .HasName("pk_homeworks");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_homeworks_lesson_id");

                    b.ToTable("homeworks", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.HomeworkSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiFeedbackDraft")
                        .HasColumnType("text")
                        .HasColumnName("ai_feedback_draft");

                    b.Property<Guid?>("GradeValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_value_id");

                    b.Property<Guid>("HomeworkId")
                        .HasColumnType("uuid")
                        .HasColumnName("homework_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<string>("SubmissionData")
                        .HasColumnType("text")
                        .HasColumnName("submission_data");

                    b.Property<string>("TeacherFeedback")
                        .HasColumnType("text")
                        .HasColumnName("teacher_feedback");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_homework_submissions");

                    b.HasIndex("GradeValueId")
                        .HasDatabaseName("ix_homework_submissions_grade_value_id");

                    b.HasIndex("HomeworkId")
                        .HasDatabaseName("ix_homework_submissions_homework_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_homework_submissions_student_id");

                    b.ToTable("homework_submissions", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentBlocks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_blocks");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_lessons_module_id");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.LessonComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.HasKey("Id")
                        .HasName("pk_lesson_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_lesson_comments_author_id");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_lesson_comments_lesson_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_lesson_comments_parent_comment_id");

                    b.ToTable("lesson_comments", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.LessonNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lesson_notes");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_lesson_notes_lesson_id");

                    b.HasIndex("StudentId", "LessonId")
                        .IsUnique()
                        .HasDatabaseName("ix_lesson_notes_student_id_lesson_id");

                    b.ToTable("lesson_notes", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.LessonRecording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_lesson_recordings");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_lesson_recordings_lesson_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_lesson_recordings_teacher_id");

                    b.ToTable("lesson_recordings", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.MessageReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DirectMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("direct_message_id");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<Guid?>("RoomMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_message_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_message_reactions");

                    b.HasIndex("DirectMessageId")
                        .HasDatabaseName("ix_message_reactions_direct_message_id");

                    b.HasIndex("RoomMessageId")
                        .HasDatabaseName("ix_message_reactions_room_message_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_message_reactions_user_id");

                    b.ToTable("message_reactions", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_modules");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_modules_course_id");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.ParentStudent", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("ParentId", "StudentId")
                        .HasName("pk_parent_students");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_parent_students_student_id");

                    b.ToTable("parent_students", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("ExternalTxId")
                        .HasColumnType("text")
                        .HasColumnName("external_tx_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_transactions");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_payment_transactions_course_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_payment_transactions_student_id");

                    b.ToTable("payment_transactions", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_push_subscriptions_user_id");

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.QuestionBankItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_question_bank_items");

                    b.ToTable("question_bank_items", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_rooms_course_id");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_rooms_host_id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.RoomMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_room_messages");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_room_messages_room_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_room_messages_user_id");

                    b.ToTable("room_messages", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_schedules_lesson_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_schedules_teacher_id");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.ShopItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CoinsPrice")
                        .HasColumnType("integer")
                        .HasColumnName("coins_price");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxPerStudent")
                        .HasColumnType("integer")
                        .HasColumnName("max_per_student");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_shop_items");

                    b.ToTable("shop_items", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.ShopPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContextCourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("context_course_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_shop_purchases");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_shop_purchases_item_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_shop_purchases_student_id");

                    b.ToTable("shop_purchases", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.StudentBadge", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<DateTimeOffset>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.HasKey("StudentId", "BadgeId")
                        .HasName("pk_student_badges");

                    b.HasIndex("BadgeId")
                        .HasDatabaseName("ix_student_badges_badge_id");

                    b.ToTable("student_badges", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.StudentDailyQuest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_student_daily_quests");

                    b.HasIndex("QuestId")
                        .HasDatabaseName("ix_student_daily_quests_quest_id");

                    b.HasIndex("StudentId", "QuestId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_student_daily_quests_student_id_quest_id_date");

                    b.ToTable("student_daily_quests", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.StudentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_student_groups");

                    b.ToTable("student_groups", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.StudentStreak", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<DateOnly>("LastActivityDate")
                        .HasColumnType("date")
                        .HasColumnName("last_activity_date");

                    b.Property<int>("MaxStreak")
                        .HasColumnType("integer")
                        .HasColumnName("max_streak");

                    b.Property<int>("TotalCoins")
                        .HasColumnType("integer")
                        .HasColumnName("total_coins");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer")
                        .HasColumnName("total_xp");

                    b.HasKey("StudentId")
                        .HasName("pk_student_streaks");

                    b.ToTable("student_streaks", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedStudentIds")
                        .HasColumnType("text")
                        .HasColumnName("allowed_student_ids");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<decimal>("PassingPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("passing_percentage");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("questions");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tests");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_tests_lesson_id");

                    b.ToTable("tests", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.TestAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers_json");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<decimal>("ScorePercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("score_percentage");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.HasKey("Id")
                        .HasName("pk_test_attempts");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_test_attempts_student_id");

                    b.HasIndex("TestId")
                        .HasDatabaseName("ix_test_attempts_test_id");

                    b.ToTable("test_attempts", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerifyToken")
                        .HasColumnType("text")
                        .HasColumnName("email_verify_token");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("TelegramId")
                        .HasColumnType("text")
                        .HasColumnName("telegram_id");

                    b.Property<string>("TelegramLinkCode")
                        .HasColumnType("text")
                        .HasColumnName("telegram_link_code");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.UserCustomValue", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.HasKey("UserId", "FieldId")
                        .HasName("pk_user_custom_values");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("ix_user_custom_values_field_id");

                    b.ToTable("user_custom_values", (string)null);
                });

            modelBuilder.Entity("LTropik.Domain.Entities.AppNotification", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.AttendanceAndGrade", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.GradeScaleValue", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .HasConstraintName("fk_attendance_and_grades_grade_scale_values_grade_id");

                    b.HasOne("LTropik.Domain.Entities.Lesson", "Lesson")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_and_grades_lessons_lesson_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_and_grades_users_student_id");

                    b.Navigation("Grade");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Bookmark", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Course", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.GradeScale", "GradeScale")
                        .WithMany("Courses")
                        .HasForeignKey("GradeScaleId")
                        .HasConstraintName("fk_courses_grade_scales_grade_scale_id");

                    b.Navigation("GradeScale");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.CourseProgress", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_progresses_lessons_lesson_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_progresses_users_student_id");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.CourseReview", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_reviews_courses_course_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_reviews_users_student_id");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.CourseStudent", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_students_courses_course_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany("EnrolledCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_students_users_student_id");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.CourseTeacher", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Course", "Course")
                        .WithMany("Teachers")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_teachers_courses_course_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Teacher")
                        .WithMany("TeachingCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_teachers_users_teacher_id");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.DirectMessage", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_direct_messages_users_receiver_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_direct_messages_users_sender_id");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.EnrollmentRequest", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_requests_courses_course_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_requests_users_student_id");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Flashcard", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.FlashcardSet", "Set")
                        .WithMany("Cards")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flashcards_flashcard_sets_set_id");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.FlashcardSet", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_flashcard_sets_lessons_lesson_id");

                    b.HasOne("LTropik.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flashcard_sets_users_user_id");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.GradeScaleValue", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.GradeScale", "Scale")
                        .WithMany("Values")
                        .HasForeignKey("ScaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grade_scale_values_grade_scales_scale_id");

                    b.Navigation("Scale");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.StudentGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_student_groups_group_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_users_student_id");

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Homework", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Homeworks")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_homeworks_lessons_lesson_id");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.HomeworkSubmission", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.GradeScaleValue", "GradeValue")
                        .WithMany()
                        .HasForeignKey("GradeValueId")
                        .HasConstraintName("fk_homework_submissions_grade_scale_values_grade_value_id");

                    b.HasOne("LTropik.Domain.Entities.Homework", "Homework")
                        .WithMany("Submissions")
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_homework_submissions_homeworks_homework_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany("HomeworkSubmissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_homework_submissions_users_student_id");

                    b.Navigation("GradeValue");

                    b.Navigation("Homework");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_modules_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.LessonComment", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_comments_users_author_id");

                    b.HasOne("LTropik.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_comments_lessons_lesson_id");

                    b.HasOne("LTropik.Domain.Entities.LessonComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lesson_comments_lesson_comments_parent_comment_id");

                    b.Navigation("Author");

                    b.Navigation("Lesson");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.LessonNote", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_notes_lessons_lesson_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_notes_users_student_id");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.LessonRecording", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_recordings_lessons_lesson_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_recordings_users_teacher_id");

                    b.Navigation("Lesson");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.MessageReaction", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.DirectMessage", "DirectMessage")
                        .WithMany()
                        .HasForeignKey("DirectMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_message_reactions_direct_messages_direct_message_id");

                    b.HasOne("LTropik.Domain.Entities.RoomMessage", "RoomMessage")
                        .WithMany()
                        .HasForeignKey("RoomMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_message_reactions_room_messages_room_message_id");

                    b.HasOne("LTropik.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_reactions_users_user_id");

                    b.Navigation("DirectMessage");

                    b.Navigation("RoomMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Module", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modules_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.ParentStudent", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.User", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parent_students_users_parent_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parent_students_users_student_id");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Course", "Course")
                        .WithMany("Transactions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payment_transactions_courses_course_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_transactions_users_student_id");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.PushSubscription", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Room", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rooms_courses_course_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_users_host_id");

                    b.Navigation("Course");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.RoomMessage", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Room", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_messages_rooms_room_id");

                    b.HasOne("LTropik.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_room_messages_users_user_id");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedules_lessons_lesson_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schedules_users_teacher_id");

                    b.Navigation("Lesson");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.ShopPurchase", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.ShopItem", "Item")
                        .WithMany("Purchases")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_purchases_shop_items_item_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_purchases_users_student_id");

                    b.Navigation("Item");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.StudentBadge", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Badge", "Badge")
                        .WithMany("StudentBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_badges_badges_badge_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_badges_users_student_id");

                    b.Navigation("Badge");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.StudentDailyQuest", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.DailyQuest", "Quest")
                        .WithMany("StudentQuests")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_daily_quests_daily_quests_quest_id");

                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_daily_quests_users_student_id");

                    b.Navigation("Quest");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.StudentStreak", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_streaks_users_student_id");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Test", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Tests")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tests_lessons_lesson_id");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.TestAttempt", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.User", "Student")
                        .WithMany("TestAttempts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_attempts_users_student_id");

                    b.HasOne("LTropik.Domain.Entities.Test", "Test")
                        .WithMany("Attempts")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_attempts_tests_test_id");

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.UserCustomValue", b =>
                {
                    b.HasOne("LTropik.Domain.Entities.CustomProfileField", "Field")
                        .WithMany("Values")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_custom_values_custom_profile_fields_field_id");

                    b.HasOne("LTropik.Domain.Entities.User", "User")
                        .WithMany("CustomValues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_custom_values_users_user_id");

                    b.Navigation("Field");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Badge", b =>
                {
                    b.Navigation("StudentBadges");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Course", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("Reviews");

                    b.Navigation("Students");

                    b.Navigation("Teachers");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.CustomProfileField", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.DailyQuest", b =>
                {
                    b.Navigation("StudentQuests");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.FlashcardSet", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.GradeScale", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Homework", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Homeworks");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.LessonComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Module", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Room", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.ShopItem", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.StudentGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.Test", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("LTropik.Domain.Entities.User", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("CustomValues");

                    b.Navigation("EnrolledCourses");

                    b.Navigation("HomeworkSubmissions");

                    b.Navigation("TeachingCourses");

                    b.Navigation("TestAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
